---
- name: Base config
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: Set timezone
      community.general.timezone:
        name: Europe/Oslo

    - name: Install packages
      ansible.builtin.apt:
        update_cache: true
        name: "{{ base_packages }}"
