---
- name: Server info
  hosts: all
  become: yes
  become_user: root
  gather_facts: true

  tasks:
    - name: "Fetch uptime"
      shell: uptime
      register: uptime

    - name: "Collect root volume disk usage"
      set_fact:
        root_free: "{{ (item.size_available / 1024 / 1024 / 1024)|round(2) }}"
        root_size: "{{ (item.size_total / 1024 / 1024 / 1024)|round(2) }}"
      when: item.mount == '/'
      with_items:
        - "{{ ansible_mounts }}"
      loop_control:
        label: "{{ item.mount }}"

    - name: Display info
      debug:
        msg:
          - "Release: {{ hostvars[inventory_hostname]['ansible_lsb']['description'] }}"
          - "IPv4: {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
          - "IPv6: {{ hostvars[inventory_hostname]['ansible_default_ipv6']['address'] }}"
          - "Uptime: {{ uptime.stdout_lines }}"
          - "Root disk usage: {{ root_free }}GB of {{ root_size }}GB available"
