---
- name: Create users
  hosts: all
  become: true
  gather_facts: false
  vars_files:
          - vars/secrets.yaml
  vars:
          username: larserik
          userpass: "{{ larserik_password }}"
  tasks:
          - name: Create user larserik
            ansible.builtin.user:
                    name: "{{ username }}"
                    state: present
                    shell: /bin/bash
                    password: "{{ userpass | password_hash('sha512') }}"
                    update_password: on_create
                    groups: sudo
                    append: yes

          - name: Deploy SSH keys
            ansible.posix.authorized_key:
                    user: "{{ username }}"
                    state: present
                    key: "{{ lookup('file', item) }}"
            with_fileglob:
                    - "config/ssh_keys/*.pub"
